openapi: 3.0.1
info:
  title: Mini Search Engine API
  version: 0.1.0
paths:
  /api/query:
    get:
      summary: submit a query
      operationId: query
      parameters:
        - name: q
          in: query
          description: string to search for
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: page of results to fetch, default 1
          schema:
            type: integer
      responses:
        "200":
          description: successful operation, result mustn't be empty
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultPage"
        "404":
          description: no results
  /api/complete:
    get:
      summary: get list of completions
      operationId: complete
      parameters:
        - name: q
          in: query
          description: string to search for
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation, result mustn't be empty
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404":
          description: no results
  /api/image/query:
    get:
      summary: get list of urls to images that are associated with given search terms
      operationId: imageQuery
      parameters:
        - name: q
          in: query
          description: string to search for
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: page of results to fetch, default 1
          schema:
            type: integer
      responses:
        "200":
          description: successful operation, result mustn't be empty
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultPage"
        "404":
          description: no results
  /api/trends:
    get:
      summary: get list of 10 most searched persons of given country.
      operationId: trends
      parameters:
        - name: country 
          in: query
          description: country alpha-3 code (ISO 3166) all capital
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation, result mustn't be empty
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404":
          description: invalid country code
components:
  schemas:
    ResultPage:
      type: object
      title: ResultPage
      properties:
        currentPage:
          type: integer
        totalPages:
          type: integer
        results:
          type: array
          items:
            $ref: "#/components/schemas/QueryResult"
    QueryResult:
      type: object
      title: QueryResult
      properties:
        title:
          type: string
        link:
          type: string
        snippet:
          type: string
